# Generated by Django 5.2.4 on 2025-07-28 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_subscriptionrequest_delete_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('plan_id', models.CharField(choices=[('30', '30 Days'), ('90', '90 Days')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SubscriptionRequest',
        ),
    ]
