# Generated by Django 5.2.4 on 2025-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_article_image_article_location_article_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
