# Generated by Django 5.2.4 on 2025-07-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_premium',
        ),
    ]
